env:
  browser: true
  es6: true
  webextensions: true
  jest: true
extends:
  - plugin:jest/recommended
plugins:
  - jest
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  browser: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  no-console: off
}

